# .github/workflows/deploy-pages.yml
name: Deploy to GitHub Pages

# Re-deploy every time something is pushed to main
on:
  push:
    branches: [ "main" ]

# The new Pages actions require these top-level permissions
permissions:
  contents: read        # to checkout the code
  pages: write          # to push to gh-pages
  id-token: write       # to authenticate the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repo
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

   
      - name: Upload static site
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs       

      # 4) Deploy!
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
